#!/bin/bash
sbatch --cpus-per-task=48 --array=1 --nodes=1 --ntasks=1 --exclude=kratos[4,6-10] --workdir=/mnt/panzer/rumpfm/filter-final --output=/mnt/panzer/rumpfm/filter-final/results/HiFi_mapped_top.out --error=/mnt/panzer/rumpfm/filter-final/results/HiFi_mapped_top.err --job-name='Hmt' --verbose --partition=slurm_part final_run.sh /mnt/panzer/rumpfm/stemmed-pairs/HiFi_mapped_100k_top.tss 10000 HiFi_mapped_top 0 10 40000
sbatch --cpus-per-task=48 --array=1 --nodes=1 --ntasks=1 --exclude=kratos[4,6-10] --workdir=/mnt/panzer/rumpfm/filter-final --output=/mnt/panzer/rumpfm/filter-final/results/HiFi_mapped_bottom.out --error=/mnt/panzer/rumpfm/filter-final/results/HiFi_mapped_bottom.err --job-name='Hmb' --verbose --partition=slurm_part final_run.sh /mnt/panzer/rumpfm/stemmed-pairs/HiFi_mapped_100k_bottom.tss 90000 HiFi_mapped_bottom 0 10 2200
sbatch --cpus-per-task=48 --array=1 --nodes=1 --ntasks=1 --exclude=kratos[4,6-10] --workdir=/mnt/panzer/rumpfm/filter-final --output=/mnt/panzer/rumpfm/filter-final/results/HiFi_chained_top.out --error=/mnt/panzer/rumpfm/filter-final/results/HiFi_chained_top.err --job-name='Hct' --verbose --partition=slurm_part final_run.sh /mnt/panzer/rumpfm/stemmed-pairs/HiFi_chained_100k_top.tss 9999 HiFi_chained_top 0 10 35000
sbatch --cpus-per-task=48 --array=1 --nodes=1 --ntasks=1 --exclude=kratos[4,6-10] --workdir=/mnt/panzer/rumpfm/filter-final --output=/mnt/panzer/rumpfm/filter-final/results/HiFi_chained_bottom.out --error=/mnt/panzer/rumpfm/filter-final/results/HiFi_chained_bottom.err --job-name='Hcb' --verbose --partition=slurm_part final_run.sh /mnt/panzer/rumpfm/stemmed-pairs/HiFi_chained_100k_bottom.tss 90001 HiFi_chained_bottom 0 10 2500
sbatch --cpus-per-task=48 --array=1 --nodes=1 --ntasks=1 --exclude=kratos[4,6-10] --workdir=/mnt/panzer/rumpfm/filter-final --output=/mnt/panzer/rumpfm/filter-final/results/Illumina_mapped_top.out --error=/mnt/panzer/rumpfm/filter-final/results/Illumina_mapped_top.err --job-name='Imt' --verbose --partition=slurm_part final_run.sh /mnt/panzer/rumpfm/stemmed-pairs/Illumina_mapped_10M_top.tss 874877 Illumina_mapped_top 0 10 400
sbatch --cpus-per-task=48 --array=1 --nodes=1 --ntasks=1 --exclude=kratos[4,6-10] --workdir=/mnt/panzer/rumpfm/filter-final --output=/mnt/panzer/rumpfm/filter-final/results/Illumina_mapped_bottom.out --error=/mnt/panzer/rumpfm/filter-final/results/Illumina_mapped_bottom.err --job-name='Imb' --verbose --partition=slurm_part final_run.sh /mnt/panzer/rumpfm/stemmed-pairs/Illumina_mapped_10M_bottom.tss 9125123 Illumina_mapped_bottom 0 10 185
sbatch --cpus-per-task=48 --array=1 --nodes=1 --ntasks=1 --exclude=kratos[4,6-10] --workdir=/mnt/panzer/rumpfm/filter-final --output=/mnt/panzer/rumpfm/filter-final/results/Illumina_chained_top.out --error=/mnt/panzer/rumpfm/filter-final/results/Illumina_chained_top.err --job-name='Ict' --verbose --partition=slurm_part final_run.sh /mnt/panzer/rumpfm/stemmed-pairs/Illumina_chained_10M_top.tss 926785 Illumina_chained_top 0 10 400
sbatch --cpus-per-task=48 --array=1 --nodes=1 --ntasks=1 --exclude=kratos[4,6-10] --workdir=/mnt/panzer/rumpfm/filter-final --output=/mnt/panzer/rumpfm/filter-final/results/Illumina_chained_bottom.out --error=/mnt/panzer/rumpfm/filter-final/results/Illumina_chained_bottom.err --job-name='Icb' --verbose --partition=slurm_part final_run.sh /mnt/panzer/rumpfm/stemmed-pairs/Illumina_chained_10M_bottom.tss 9073215 Illumina_chained_bottom 0 10 180
